import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/styles/themes.css";
import "@/styles/globals.css";
import "@/styles/globals-medium.css";
import "@/styles/globals-large.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";

const poppins = Poppins({
  weight: '400',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: "Gateway Games Alaska",
  description: "Generated by create next app",
};

const preferredTheme = 'dark'

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${preferredTheme}`}>
      <body
        className={`${poppins.className} antialiased`}
      >
        <Header />
        <main>
          {children}
        </main>
        <Footer />
      </body>
    </html>
  );
}
